version: '3.3'
networks:
  elk:
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.1.3'
    container_name: elasticsearch
    networks:
      - elk
    volumes:
      - /home/xushikuan/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xmx1024m -Xms1024m"

  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.1.3'
    container_name: kibana
    networks:
      - elk
    ports:
      - '5601:5601'
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch

  logstash:
    image: 'docker.elastic.co/logstash/logstash:6.1.3'
    container_name: logstash
    networks:
      - elk
    ports:
      - '5000:5000'
    links:
      - elasticsearch:elasticsearch
    environment:
      - DROP_NON_JSON=false
      - STDOUT=true
    volumes:
      - /home/xushikuan/sillyhat-elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch


