version: '3.6'
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.1.3'
    volumes:
      - /home/xushikuan/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.1.3'
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

