version: '3.3'
services:
  logspout:
    image: gliderlabs/logspout:v3
    command: 'syslog+tcp://172.16.99.130:5000'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    #image: gliderlabs/logspout:v3
    #command: 'syslog://logstash:5000'
    #links:
    #  - logstash
    #volumes:
    #  - '/var/run/docker.sock:/tmp/docker.sock'

  logstash:
    image: ludekvesely/logstash-json
    environment:
      - LOGSPOUT=ignore
      - DROP_NON_JSON=false
      - STDOUT=true
    links:
      - elasticsearch

  kibana:
    image: kibana
    environment:
      - LOGSPOUT=ignore
    links:
      - elasticsearch
    ports:
      - '5601:5601'

  elasticsearch:
    image: elasticsearch
    environment:
      - LOGSPOUT=ignore